{"name": "编辑用户手机号为异常号码", "status": "passed", "description": "编辑用户手机号为异常号码", "attachments": [{"name": "log", "source": "ac07677c-dbbb-4403-a6e0-46c3370bd6b8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '编辑用户手机号为异常号码', 'nickname': '刘子编辑', 'phone': 1595485421655, 'real_name': '刘子编辑', 'identities': 5, 'gender': 2, 'stu_no': 9658}"}], "start": 1723611313243, "stop": 1723611313458, "uuid": "d8361a59-5485-471e-b3a3-51b5cdca28f2", "historyId": "2ad69d55c68046fabfdd9b7bea2e5879", "testCaseId": "f83ac5b0bdd72330d7bfd52b3edea55e", "fullName": "testcases.test_user_manage_api.TestUserManageApi#test_edit_user_abnormal", "labels": [{"name": "feature", "value": "用户管理模块"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "编辑用户手机号为异常号码测试用例"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_user_manage_api"}, {"name": "subSuite", "value": "TestUserManageApi"}, {"name": "host", "value": "常胜峰"}, {"name": "thread", "value": "5484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_user_manage_api"}]}