{"name": "编辑用户手机号为异常号码", "status": "passed", "description": "编辑用户手机号为异常号码", "attachments": [{"name": "log", "source": "b302e4eb-a0b0-4ec6-8326-b1b97e096801-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '编辑用户手机号为异常号码', 'nickname': '刘子编辑', 'phone': 1595485421655, 'real_name': '刘子编辑', 'identities': 5, 'gender': 2, 'stu_no': 9658}"}], "start": 1723443999024, "stop": 1723443999264, "uuid": "d6a37391-aa69-4625-a239-9c5653dfc930", "historyId": "2ad69d55c68046fabfdd9b7bea2e5879", "testCaseId": "f83ac5b0bdd72330d7bfd52b3edea55e", "fullName": "testcases.test_user_manage_api.TestUserManageApi#test_edit_user_abnormal", "labels": [{"name": "feature", "value": "用户管理模块"}, {"name": "story", "value": "编辑用户手机号为异常号码测试用例"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_user_manage_api"}, {"name": "subSuite", "value": "TestUserManageApi"}, {"name": "host", "value": "常胜峰"}, {"name": "thread", "value": "8300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_user_manage_api"}]}